// Generates the deployable index.html from the .dc.html source.
// No dependencies — run with: node build.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const SRC = 'Camm Plastering Website v2.dc.html';
const OUT = 'index.html';

const TITLE = 'Camm Plastering Contractors Ltd — Plastering, Drylining & Rendering';
const DESCRIPTION =
  'Full plastering, drylining, rendering and screeding packages for national housebuilders, ' +
  'main contractors and private clients across South Yorkshire, Derbyshire and Nottinghamshire. ' +
  'Based in Worksop. CHAS accredited, SSIP registered, CSCS-carded.';

/** Replace `find` exactly once, or fail loudly so a source edit can't silently break the build. */
function replaceOnce(html, find, replace, label) {
  const parts = html.split(find);
  if (parts.length !== 2) {
    throw new Error(`build: expected exactly 1 match for "${label}", found ${parts.length - 1}`);
  }
  return parts.join(replace);
}

let html = readFileSync(SRC, 'utf8');

// The "TO CONFIRM" note bar is an internal review aid — its own copy says it
// won't appear on the live site, so default it off in the published build.
html = replaceOnce(
  html,
  '&quot;showConfirmNotes&quot;:{&quot;editor&quot;:&quot;boolean&quot;,&quot;default&quot;:true',
  '&quot;showConfirmNotes&quot;:{&quot;editor&quot;:&quot;boolean&quot;,&quot;default&quot;:false',
  'showConfirmNotes prop default',
);
html = replaceOnce(
  html,
  'showConfirmNotes: this.props.showConfirmNotes ?? true,',
  'showConfirmNotes: this.props.showConfirmNotes ?? false,',
  'showConfirmNotes runtime fallback',
);

// The source has no <title>/description — a deployed page needs both.
html = replaceOnce(
  html,
  '<meta name="viewport" content="width=device-width, initial-scale=1">',
  '<meta name="viewport" content="width=device-width, initial-scale=1">\n' +
    `<title>${TITLE}</title>\n` +
    `<meta name="description" content="${DESCRIPTION}">\n` +
    '<link rel="icon" href="assets/camm-logo.png">',
  'head meta block',
);

const banner =
  '<!-- GENERATED by build.mjs from "' + SRC + '" — do not edit by hand. -->\n';
writeFileSync(OUT, banner + html);
console.log(`build: wrote ${OUT} from "${SRC}"`);
